
[config]

file_path = '/mnt/d/Documents/git_down/monitor_process_io/test/main'
argv = '12345'
arch = '64'

[[plugin]]

syscall_number = 0
name = 'read_default'
argv_num = 1
argv1 = 'plugin_default.log'

[[plugin]]

syscall_number = 1
name = 'write_default'
argv_num = 1
argv1 = 'plugin_default.log'